name: reviewdog
on: [push]
jobs:
  stylelint:
    name: runner / stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: stylelint
        uses: acrollet/action-stylelint@v1
        with:
          github_token: ${{ secrets.github_token }}
          packages: 'stylelint-config-sass-guidelines stylelint-order'
          reporter: github-pr-review
          stylelint_config: '.stylelintrc'
          stylelint_input: 'check/*.scss'

